export const API_LOGIN = '/login'
export const API_REGISTRATION = '/registration'
export const API_SEND_FORGET_PASSWORD_OTP = '/send-forget-password-otp'
export const API_RESET_PASSWORD = '/reset-password'
export const API_CHANGE_PASSWORD = '/change-password'
export const API_USER_INFORMATION = '/me'